--- # Poggit-CI Manifest. Open the CI at http://90.116.51.244/poggit/ci/Awzaw/EconomyS
branches:
- master
projects:
  EconomyAPI:
    path: EconomyAPI/
  EconomyAirport:
    path: EconomyAirport/
  EconomyAuction:
    path: EconomyAuction/
  EconomyCasino:
    path: EconomyCasino/
  EconomyJob:
    path: EconomyJob/
  EconomyLand:
    path: EconomyLand/
  EconomyPShop:
    path: EconomyPShop/
  EconomyProperty:
    path: EconomyProperty/
  EconomySell:
    path: EconomySell/
  EconomyShop:
    path: EconomyShop/
  EconomyTax:
    path: EconomyTax/
  EconomyUsury:
    path: EconomyUsury/
...
