---
branches: master
projects:
  EconomyAPI.plugin.yml:
    path: EconomyAPI/
    model: default
  EconomyAirport.plugin.yml:
    path: EconomyAirport/
    model: default
  EconomyAuction.plugin.yml:
    path: EconomyAuction/
    model: default
  EconomyCasino.plugin.yml:
    path: EconomyCasino/
    model: default
  EconomyJob.plugin.yml:
    path: EconomyJob/
    model: default
  EconomyLand.plugin.yml:
    path: EconomyLand/
    model: default
  EconomyPShop.plugin.yml:
    path: EconomyPShop/
    model: default
  EconomyProperty.plugin.yml:
    path: EconomyProperty/
    model: default
  EconomySell.plugin.yml:
    path: EconomySell/
    model: default
  EconomyShop.plugin.yml:
    path: EconomyShop/
    model: default
  EconomyTax.plugin.yml:
    path: EconomyTax/
    model: default
  EconomyUsury.plugin.yml:
    path: EconomyUsury/
    model: default
...
